apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend
  labels:
    app: users-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: users-backend
  template:
    metadata:
      labels:
        app: users-backend
    spec:
      containers:
        - name: users-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
