apiVersion: v1
kind: Service
metadata:
  name: users-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: users-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
