services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - ./backend/users-service/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # eureka-server:
  #   build: ./backend/users-service/eureka-server
  #   container_name: eureka-server
  #   restart: always
  #   ports:
  #     - "8761:8761"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30

  users-service:
    build: ./backend/users-service
    container_name: users-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      # eureka-server:
      #   condition: service_healthy

  frontend:
    build: ./frontend
    container_name: users-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      users-service:
        condition: service_started
