spring:
  application:
    name: users-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://mysql-db:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user       # matches MYSQL_USER in docker-compose
    password: user123    # matches MYSQL_PASSWORD in docker-compose

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.userservice: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    enabled: true

# # Eureka client configuration
# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka-server:8761/eureka/
#     register-with-eureka: true
#     fetch-registry: true
