apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AniketDewangan/User_service_app.git
    targetRevision: HEAD
    path: helm/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
