apiVersion: v1
kind: Service
metadata:
  name: users-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: users-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
