replicaCount: 1

image:
  repository: kd57/users-backend
  pullPolicy: IfNotPresent
  tag: v1.1

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysql-db:3306/userdb
  - name: SPRING_DATASOURCE_USERNAME
    value: user
  - name: SPRING_DATASOURCE_PASSWORD
    value: user123

resources: {}
