version: "3.9"

services:
  notebook:
    build: .
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
    environment:
      # Set your own secure token (then open http://localhost:8888/?token=YOUR_TOKEN)
      JUPYTER_TOKEN: "lab"   # <-- change this if you want
      # Optional Spark JVM opts
      SPARK_OPTS: "--driver-memory 4g --executor-memory 4g"
    # Mount your local folders:
    volumes:
      # Your notebooks live here (you’ll open them inside Jupyter)
      - ./workspace:/home/jovyan/work
      # Your CSVs live here; code reads /mnt/data/*.csv
      - ./data:/mnt/data
    depends_on:
      - mysql

  # Optional MySQL for landing Bronze/Silver/Gold (via JDBC)
  mysql:
    image: mysql:8.4
    container_name: medallion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medallion
    command: >
      --default-authentication-plugin=mysql_native_password
      --lower-case-table-names=1
      --sql-mode=""
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
